language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x

before_install:
  - go get -v ./...

install: 
  - go test -v -benchmem -bench . -coverprofile=/tmp/go-code-bench

after_success:
  - bash <(curl -s https://codecov.io/bash)